# Generated by Django 3.0.5 on 2020-05-02 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sharding.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('desc', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Normal product',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('nid', models.CharField(db_index=True, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('desc', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('vendor', sharding.fields.ShardedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('nid', models.CharField(db_index=True, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('desc', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('products', sharding.fields.ShardedManyToManyField(db_constraint=False, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Store',
            },
        ),
        migrations.CreateModel(
            name='NormalStoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stores', models.CharField(db_index=True, max_length=36)),
                ('products', models.ManyToManyField(db_constraint=False, db_index=True, to='shop.NormalProductModel')),
            ],
            options={
                'verbose_name': 'Normal store',
            },
        ),
    ]
