# Generated by Django 3.0.5 on 2020-04-29 22:35

from django.db import migrations
import sharding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=sharding.fields.ShardedManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
