# Generated by Django 3.0.5 on 2020-05-02 11:28

from django.db import migrations
import sharding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_store_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='products',
            field=sharding.fields.ShardedManyToManyField(to='shop.Product'),
        ),
    ]
