# Generated by Django 3.0.5 on 2020-05-02 12:18

from django.db import migrations
import sharding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_store_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='products',
            field=sharding.fields.ShardedManyToManyField(db_constraint=False, to='shop.Product'),
        ),
    ]
