# Generated by Django 3.0.5 on 2020-05-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, editable=False, max_length=8, unique=True)),
                ('model_name', models.CharField(db_index=True, max_length=20)),
                ('number', models.IntegerField(db_index=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
