# Generated by Django 3.0.5 on 2020-05-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('shardeduser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sharding.ShardedUser')),
            ],
            options={
                'abstract': False,
            },
            bases=('sharding.shardeduser',),
        ),
    ]
