# Generated by Django 3.0.5 on 2020-05-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sharding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('nid', models.CharField(db_index=True, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', sharding.fields.ShardedOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nid'],
                'abstract': False,
            },
        ),
    ]
