# Generated by Django 3.0.5 on 2020-05-05 11:30

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import sharding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=sharding.fields.ShardedOneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
